globals:
    cf_api_key: ENC[AES256_GCM,data:ZWt4lyLa/Qjzwrn+vmrSzRCWxIcWmd4oAs/ccljKO3RjIWvcAQ==,iv:v2mMtzxar+RxdcNM4X2hvIDakeNCCOXJvH0L81mXJM4=,tag:J86Mwr7iiNgZbzpRYX6jUA==,type:str]
roles:
    base:
        foo: ENC[AES256_GCM,data:Jw20,iv:053wBZDckiySo7AW3XhxHz1BC0xzVQcVcUXVg7OpVwE=,tag:QOOlDzh3Zp65D+7M1oPfWw==,type:str]
components:
    podman_exporter:
        port: ENC[AES256_GCM,data:sl+v4g==,iv:/hChZ3P6ifnvF3Xddk9PATdASzJypezm2IFMB2VluDU=,tag:AnlAHV0Lop5aQk1vCXz6GQ==,type:int]
hosts:
    sophie:
        traefik_domain: ENC[AES256_GCM,data:FUNhTZFDt88Fcr3ddzs=,iv:5ZaCh7O6W8BESbhVOj5WxJTslCJcAxzXhLOkRYX4Xqo=,tag:D0a6ohynwF3tw9FW/gHwnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaktEV0Q5dzU0TDRXOEZS
            aWYxVzNkUlgrZW9TUnF4cWc0UlFVT090MXdvCkNVd3Fic2d6WTAvL2R2dFA5dzRV
            WXgyVlJTSGlObEZBeWpaOUkvR29idDQKLS0tIDQrcktuZEVKNGpKUmxJWDllcmJZ
            VmhtdkdQeFFYaVJpUXpha0tTbTdTTnMKgRCsEaAQKHCbNFBAVmqMSqnLLmZbALvF
            B7b1o+Aun4sn6mYYIT+EsJF7tzUXqmzGbXT3OVF+w1LZ3EoUf566DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149kknsv5hardn4pmgkfkmd9749cmkux6pthc27ms567zhae5q5vsl97708
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweDIzTldXdGJ6eFdXVW9q
            T2VkZ1BxNzJNNnQzZkFDZWVvT2dWbm9yckVZClNRSVdoODlpeXpxSk5URXA1Vzh2
            c0tjUGZRbmhocmhRazBYMFdhWXhyckUKLS0tIHNaQ1FmRS9mVXNQSEREY3JML0lE
            UkdrQ2QvTWIzZ1ZvY2pMcjlmTnBpSkEKHUC1vXDVdZ0Ktj7rKP4Os1YMxM32545a
            wYpNUZKOi1k7fd/b4iAHHsKV2b5i7NJ9VYI/XnEvGW5/I0LZyB/Qrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1af5h8gys22a7wets8uxt6nts2anye6esqgvvuw9zn5zjttn6sdqq062knr
    lastmodified: "2026-06-15T09:24:39Z"
    mac: ENC[AES256_GCM,data:4Y6+Z8817b7AZ58JLMB+CuiQXFivLOdAk/FzrxI4gFlsRXcWFZRaQ52sglYiVs8o7WxCmgmA5QAM1EDOpJQJ+zUI3nWevCsdlSBnw0nRvWTwVw4LYn8NnuuGNIE9OBzniOLx9kCV1qj5newOMy2rFeKOUpez/e0mkmoAD4zzCGc=,iv:LdKtVaYp0eXBBR62Ad06duc5U5MzZ9N82hy0iuegErY=,tag:B6BW1N9uqq5MU2Ml8g4Zew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
