components:
    podman_exporter:
        port: ENC[AES256_GCM,data:sl+v4g==,iv:/hChZ3P6ifnvF3Xddk9PATdASzJypezm2IFMB2VluDU=,tag:AnlAHV0Lop5aQk1vCXz6GQ==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaktEV0Q5dzU0TDRXOEZS
            aWYxVzNkUlgrZW9TUnF4cWc0UlFVT090MXdvCkNVd3Fic2d6WTAvL2R2dFA5dzRV
            WXgyVlJTSGlObEZBeWpaOUkvR29idDQKLS0tIDQrcktuZEVKNGpKUmxJWDllcmJZ
            VmhtdkdQeFFYaVJpUXpha0tTbTdTTnMKgRCsEaAQKHCbNFBAVmqMSqnLLmZbALvF
            B7b1o+Aun4sn6mYYIT+EsJF7tzUXqmzGbXT3OVF+w1LZ3EoUf566DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149kknsv5hardn4pmgkfkmd9749cmkux6pthc27ms567zhae5q5vsl97708
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweDIzTldXdGJ6eFdXVW9q
            T2VkZ1BxNzJNNnQzZkFDZWVvT2dWbm9yckVZClNRSVdoODlpeXpxSk5URXA1Vzh2
            c0tjUGZRbmhocmhRazBYMFdhWXhyckUKLS0tIHNaQ1FmRS9mVXNQSEREY3JML0lE
            UkdrQ2QvTWIzZ1ZvY2pMcjlmTnBpSkEKHUC1vXDVdZ0Ktj7rKP4Os1YMxM32545a
            wYpNUZKOi1k7fd/b4iAHHsKV2b5i7NJ9VYI/XnEvGW5/I0LZyB/Qrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1af5h8gys22a7wets8uxt6nts2anye6esqgvvuw9zn5zjttn6sdqq062knr
    lastmodified: "2026-05-15T10:10:46Z"
    mac: ENC[AES256_GCM,data:2w27YxZbGGSvX6x5RSS5avtWdZPTZMmNwM2QeN1qPNmB8xzEX0mEoR8Ve19g0urxlX5R7DH7Vr/aZI3vKLSCIdgba8xAd/sBcaBvotxZ384ptv6TX0Bipw8Z+8GZACZReq3MZd7eUFchizGn8hHBoerllVVYP/N7imvRmvqVTkQ=,iv:eMHWOOcxeqkV7ihHERT90pXkJb44krkZjvFxCYV63T4=,tag:rl3T8Is3NX5ne8ujw3VTLw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
